version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    container_name: server
    image: {{ env.IMAGE_URL }}
    restart: always
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data:
