basePath: /
definitions:
  model.Compaign:
    properties:
      age_from:
        type: integer
      age_to:
        type: integer
      city:
        type: string
      gender:
        type: string
      id:
        type: integer
      theme:
        type: string
      utm_campaign:
        type: string
    type: object
  model.File:
    properties:
      createAt:
        type: string
      id:
        type: integer
      name:
        type: string
      receivedAt:
        type: string
      sendAt:
        type: string
      size:
        type: integer
      status:
        type: string
      status_message:
        type: string
    required:
    - name
    type: object
  model.Lead:
    properties:
      client_id:
        type: string
      cpc:
        type: integer
      date:
        type: string
      id:
        type: integer
      product_category_name:
        type: string
      utm_campaign:
        type: string
      utm_content:
        type: string
      utm_source:
        type: string
    type: object
  model.RegionPredict:
    properties:
      city:
        type: string
      currentClientIndex:
        type: number
      id:
        type: integer
      position:
        type: integer
      predictArpu:
        type: number
      predictClientIndex:
        type: number
      predictScore:
        type: number
      product:
        type: string
    required:
    - city
    - position
    type: object
  model.ResponseError:
    properties:
      error:
        type: string
    type: object
  model.Telegram:
    properties:
      category:
        type: string
      id:
        type: integer
      n_subscribers:
        type: integer
      name:
        type: string
      name_id:
        type: string
    type: object
host: 51.250.44.134
info:
  contact: {}
  description: API for Moscow City Hack 2022.
  title: hack API
  version: "1.0"
paths:
  /v1/compaign:
    get:
      description: Получить список Компаний
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Compaign'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получить список Компаний
      tags:
      - compaign
  /v1/file:
    get:
      description: Если файл есть в расчете то получим его состояние
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.File'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получить состояние текущего файла с датасетом
      tags:
      - file
    post:
      consumes:
      - multipart/form-data
      description: Получаем файл с фронта с новым датасетом для расчета
      parameters:
      - description: form data with file
        in: formData
        minLength: 1
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.File'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Сохранить файл с датасетом
      tags:
      - file
  /v1/lead:
    get:
      description: Получить список Лидов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Lead'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получить список Лидов
      tags:
      - lead
  /v1/region/predict:
    get:
      description: Результат работы модели загружаем в этом методе
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.RegionPredict'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получить список городов с придиктивной аналитикой
      tags:
      - region
  /v1/telegram:
    get:
      description: Получить список телеграм каналов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Telegram'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получить список телеграм каналов
      tags:
      - telegram
  /ws/:
    get:
      description: Обрабатываем WebSocket
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Обрабатываем WebSocket
      tags:
      - ws
swagger: "2.0"
