basePath: /
definitions:
  model.File:
    properties:
      createAt:
        type: string
      id:
        type: integer
      name:
        type: string
      receiveAt:
        type: string
      sendAt:
        type: string
      size:
        type: number
    required:
    - name
    type: object
  model.RegionPredict:
    properties:
      city:
        type: string
      currentClientIndex:
        type: integer
      id:
        type: integer
      position:
        type: string
      predictArpu:
        type: integer
      predictClientIndex:
        type: integer
    required:
    - city
    - position
    type: object
  model.ResponseError:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Moscow City Hack 2022.
  title: hack API
  version: "1.0"
paths:
  /v1/file/:
    post:
      consumes:
      - multipart/form-data
      description: Получаем файл с фронта с новым датасетом для расчета
      parameters:
      - description: form data with file
        in: formData
        minLength: 1
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.File'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Сохранить файл с датасетом
      tags:
      - file
  /v1/region/predict:
    get:
      description: Результат работы модели загружаем в этом методе
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.RegionPredict'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получить список городов с придиктивной аналитикой
      tags:
      - region
  /ws/:
    get:
      description: Обрабатываем WebSocket
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Обрабатываем WebSocket
      tags:
      - ws
swagger: "2.0"
