basePath: /
definitions:
  model.AuthResponse:
    properties:
      access_token:
        description: AccessToken
        type: string
      refresh_token:
        description: RefreshToken
        type: string
    type: object
  model.Offer:
    properties:
      date:
        type: string
      isAvailableByLimit:
        type: boolean
      isAvailableForTrainees:
        type: boolean
      isEditable:
        type: boolean
      isMine:
        type: boolean
      limit:
        type: integer
      limitFact:
        type: integer
      offerId:
        type: integer
      waveId:
        type: integer
      waveStart:
        type: string
    type: object
  model.ResponseError:
    properties:
      error:
        type: string
    type: object
  model.ShiftsResponse:
    properties:
      offers:
        description: Массив предложний
        items:
          $ref: '#/definitions/model.Offer'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Moscow City Hack 2022.
  title: hack API
  version: "1.0"
paths:
  /broadcastShifts/:
    get:
      description: Рассылка обновления расписания веб-сокет
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ShiftsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Рассылка обновления расписания по веб-сокет
      tags:
      - ws
  /v1/login/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Авторизация пользователя с логином и паролем
      parameters:
      - description: email
        in: formData
        maxLength: 100
        minLength: 1
        name: email
        required: true
        type: string
      - description: inn
        in: formData
        maxLength: 100
        minLength: 1
        name: inn
        required: true
        type: string
      - description: password
        in: formData
        maxLength: 100
        minLength: 1
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Авторизация пользователя
      tags:
      - auth
  /v1/scheduler/:
    get:
      description: Получение доступных предложений
      parameters:
      - description: day
        in: query
        maxLength: 8
        minLength: 8
        name: day
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ShiftsResponse'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.ShiftsResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Получение доступных предложений
      tags:
      - offers
  /v1/token/:
    post:
      consumes:
      - application/json
      description: Рефреш токен
      parameters:
      - description: refresh_token
        in: formData
        minLength: 1
        name: offerId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Рефреш токен
      tags:
      - auth
  /v1/ws/:
    get:
      description: Обрабатываем WebSocket
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Обрабатываем WebSocket
      tags:
      - ws
swagger: "2.0"
