basePath: /
definitions:
  model.ResponseError:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Moscow City Hack 2022.
  title: hack API
  version: "1.0"
paths:
  /ws/:
    get:
      description: Обрабатываем WebSocket
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ResponseError'
      summary: Обрабатываем WebSocket
      tags:
      - ws
swagger: "2.0"
