// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "hack/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// RegionRepository is an autogenerated mock type for the RegionRepository type
type RegionRepository struct {
	mock.Mock
}

// PredictList provides a mock function with given fields: _a0
func (_m *RegionRepository) PredictList(_a0 context.Context) ([]model.RegionPredict, error) {
	ret := _m.Called(_a0)

	var r0 []model.RegionPredict
	if rf, ok := ret.Get(0).(func(context.Context) []model.RegionPredict); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RegionPredict)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PredictListUpdate provides a mock function with given fields: _a0, _a1
func (_m *RegionRepository) PredictListUpdate(_a0 context.Context, _a1 []model.RegionPredict) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.RegionPredict) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
